language: python

matrix:
  include:
#    - os: linux
#      env:
#        - INSTALL_LUA="lua=5.1"
#        - LUA="lua"
#    - os: linux
#      env:
#        - INSTALL_LUA="lua=5.2"
#        - LUA="lua"
    - os: linux
      env:
        - INSTALL_LUA="lua=5.3"
        - LUA="lua"
#    - os: linux
#      env:
#        - INSTALL_LUA="luajit=2.0"
#        - LUA="luajit"
#    - os: linux
#      env:
#        - INSTALL_LUA="luajit=2.1"
#        - LUA="luajit"
#    - os: osx
#      language: generic
#      env:
#        - INSTALL_LUA="lua=5.1"
#        - LUA="luajit"
#    - os: osx
#      language: generic
#      env:
#        - INSTALL_LUA="lua=5.2"
#        - LUA="luajit"
#    - os: osx
#      language: generic
#      env:
#        - INSTALL_LUA="lua=5.3"
#        - LUA="luajit"
#    - os: osx
#      language: generic
#      env:
#        - INSTALL_LUA="luajit=2.0"
#        - LUA="luajit"
#    - os: osx
#      language: generic
#      env:
#        - INSTALL_LUA="luajit=2.1"
#        - LUA="luajit"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if ! which hererocks &> /dev/null; then pip install hererocks; fi
  - if ! [[ -e ~/lua-install/bin/luarocks ]]; then hererocks lua_install -rlatest --$INSTALL_LUA; fi
  - find -L ~/lua-install
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH
  - cd lua; make linux; cd ..

install:
  - if ! luarocks show busted &> /dev/null; then luarocks install busted; fi
  - if ! luarocks show luacov &> /dev/null; then luarocks install luacov; fi
#  - luarocks install luacov-coveralls
  - luarocks make # This installs necessary runtime dependencies

script:
  - busted -c -o gtest -v spec/

#after_success:
  - luacov "titan%-compiler" "/spec/[^/]+.lua" "titanc" && bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: change

cache:
  directories:
    - $HOME/.luarocks
    - $HOME/virtualenv
    - $HOME/lua-install
